### 회원가입
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "email": "test1@example.com",
  "password": "sparta1234",
  "name": "최준영",
  "phoneNumber": "010-1234-5678"
}

### 로그인
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test1@example.com",
  "password": "sparta1234"
}

### 내 정보 조회
GET http://localhost:8080/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJ0ZXN0MUBleGFtcGxlLmNvbSIsImlhdCI6MTc4MDQ3NDY4MywiZXhwIjoxNzgwNDc4MjgzfQ.LqXjvbKjYNwhI28jgawx8wYwV5_TqjJdIg05Cvug7wc

### 내 멤버십 정보 조회
GET http://localhost:8080/api/users/me/memberships
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJ0ZXN0MUBleGFtcGxlLmNvbSIsImlhdCI6MTc4MDQ3NDY4MywiZXhwIjoxNzgwNDc4MjgzfQ.LqXjvbKjYNwhI28jgawx8wYwV5_TqjJdIg05Cvug7wc