spring:
  application:
    name: commerce-payment-application

  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: false

jwt:
  secret: ${PROD_JWT_SECRET}
  expiration: 3600000

portone:
  base-url: "https://api.portone.io"
  api-secret: ${PROD_PORTONE_API_SECRET}
  store-id: ${PROD_PORTONE_STORE_ID}
  channel-key: ${PROD_PORTONE_CHANNEL_KEY}
  webhook-secret: ${PORTONE_WEBHOOK_SECRET}